CREATE SCHEMA IF NOT EXISTS TRIP;

CREATE TABLE IF NOT EXISTS TRIP.CRUISE (
    ID BIGINT PRIMARY KEY,
    DESCRIPCIO VARCHAR(255),
    AVGSHIPRATING REAL,
    AVGROOMRATING REAL,
    AVGCREWRATING REAL,
    AVGFOODRATING REAL
);

CREATE TABLE IF NOT EXISTS TRIP.TRIP (
    ID BIGINT PRIMARY KEY,
    ROUTE VARCHAR(255),
    STARTDATE DATE,
    ENDDATE DATE,
    NDIVES INTEGER,
    PRICE REAL
);

CREATE TABLE IF NOT EXISTS TRIP.DESTINATION (
    ID BIGINT PRIMARY KEY,
    DESCRIPTION VARCHAR(255)
);

CREATE TYPE BOOKING_STATUS AS ENUM ('PENDING', 'CONFIRMED', 'REJECTED');

CREATE TABLE IF NOT EXISTS TRIP.BOOKING (
    ID BIGINT PRIMARY KEY,
    STATUS TRIP.BOOKING_STATUS
);

CREATE TABLE IF NOT EXISTS TRIP.RATING (
    ID BIGINT PRIMARY KEY,
    SHIP INTEGER CHECK (SHIP >= 0 AND SHIP <= 5),
    ROOM INTEGER CHECK (ROOM >= 0 AND ROOM <= 5),
    CREW INTEGER CHECK (CREW >= 0 AND CREW <= 5),
    FOOD INTEGER CHECK (FOOD >= 0 AND FOOD <= 5),
    COMMENT VARCHAR(255)
);