spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/?currentSchema=trips
    username: abarrena0
    password: abarrena0_tfg
    driver-class-name: org.postgresql.Driver
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
server:
  port: 8081
application:
  name: trips-service
  version: 1.0.0
  defaultLanguage: en_US