spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/?currentSchema=trips
    username: abarrena0
    password: abarrena0_tfg
    driver-class-name: org.postgresql.Driver
  main:
    allow-circular-references: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081
application:
  name: trips-service
  version: 1.0.0
  defaultLanguage: en_US