spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/?currentSchema=trip
    username: abarrena0
    password: abarrena0_tfg
    driver-class-name: org.postgresql.Driver
server:
  port: 8081
application:
  name: trip
  version: 1.0.0
  defaultLanguage: en_US