INSERT INTO DESTINATION (DESCRIPTION) VALUES ('Destination 1');
INSERT INTO DESTINATION (DESCRIPTION) VALUES ('Destination 2');

INSERT INTO CRUISE (NAME, DESCRIPTION, CAPACITY) VALUES ('Cruise 1', 'Cruise 1 description', 10);
