INSERT INTO DESTINATION (DESCRIPTION) VALUES ('Malapascua');
INSERT INTO DESTINATION (DESCRIPTION) VALUES ('Red Sea');

INSERT INTO CRUISE (NAME, DESCRIPTION) VALUES ('Cruise 1', 'Cruise 1 description');
