CREATE SCHEMA IF NOT EXISTS TRIPS;

SET SEARCH_PATH = 'TRIPS';

CREATE TABLE IF NOT EXISTS CRUISE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(5000) NOT NULL,
    CAPACITY INTEGER NOT NULL CHECK (CAPACITY > 0),
    AVG_SHIP_RATING REAL DEFAULT 0,
    AVG_ROOM_RATING REAL DEFAULT 0,
    AVG_CREW_RATING REAL DEFAULT 0,
    AVG_FOOD_RATING REAL DEFAULT 0,
    COMPANY_ID INTEGER NOT NULL,
    THUMBNAIL_ID INTEGER
);

CREATE TABLE IF NOT EXISTS DESTINATION (
    ID SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TRIP (
    ID SERIAL PRIMARY KEY,
    ROUTE VARCHAR(5000) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    DIVES INTEGER NOT NULL CHECK (DIVES >= 0),
    PRICE REAL NOT NULL CHECK (PRICE > 0),
    CRUISE_ID INTEGER NOT NULL,
    DESTINATION_ID INTEGER NOT NULL
);

ALTER TABLE TRIP ADD CONSTRAINT FK_TRIP_CRUISE FOREIGN KEY (CRUISE_ID) REFERENCES CRUISE(ID);
ALTER TABLE TRIP ADD CONSTRAINT FK_TRIP_DESTINATION FOREIGN KEY (DESTINATION_ID) REFERENCES DESTINATION(ID);

CREATE TABLE IF NOT EXISTS BOOKING (
    ID SERIAL PRIMARY KEY,
    STATUS VARCHAR(255) NOT NULL CHECK (STATUS IN ('PENDING', 'CONFIRMED', 'REJECTED')),
    TRIP_ID INTEGER NOT NULL,
    TRAVELER_ID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS RATING (
    ID SERIAL PRIMARY KEY,
    SHIP INTEGER CHECK (SHIP >= 0 AND SHIP <= 5),
    ROOM INTEGER CHECK (ROOM >= 0 AND ROOM <= 5),
    CREW INTEGER CHECK (CREW >= 0 AND CREW <= 5),
    FOOD INTEGER CHECK (FOOD >= 0 AND FOOD <= 5),
    CRUISE_ID INTEGER NOT NULL,
    COMMENT VARCHAR(255)
);

ALTER TABLE RATING ADD CONSTRAINT FK_RATING_CRUISE FOREIGN KEY (CRUISE_ID) REFERENCES CRUISE(ID);

CREATE TABLE IF NOT EXISTS CRUISE_IMAGE (
    CRUISE_ID INTEGER NOT NULL,
    IMAGE_ID INTEGER NOT NULL
);

ALTER TABLE CRUISE_IMAGE ADD CONSTRAINT PK_CRUISE_IMAGE PRIMARY KEY (CRUISE_ID, IMAGE_ID);
ALTER TABLE CRUISE_IMAGE ADD CONSTRAINT FK_CRUISE_IMAGE_CRUISE FOREIGN KEY (CRUISE_ID) REFERENCES CRUISE(ID);
